### PR TITLE
#1399 Remove dependency on Auto Entity Label (unsupported)

### PR DESCRIPTION
**Pull request by kayakr**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1399

* Other Relevant Links (Google Groups discussion, related pull requests,
 Release pull requests, etc.)

# What does this Pull Request do?

Update dependency on Auto Entity Reference to a supported version

# How should this be tested?

Our instance is well behind islandora_defaults commits, so it's not easy for me to test this just now.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Actually, this dependency isn't necessary and should just be removed. 

We used to use it for Person names, but it was a bit buggy and controversial, so we dropped the config but didn't drop the dependency.

**Comment by kayakr** [comment]
@seth-shaw-unlv Revised patch to remove dependency on Auto Entity Label.

**Comment by seth-shaw-unlv** [comment]
Can you remove the reference in `composer.json` as well? Thanks!

**Comment by kayakr** [comment]
@seth-shaw-unlv Done. Needs review, testing.

**Comment by seth-shaw-unlv** [comment]
Yup. Hopefully I can do that tomorrow.

**Pull request merged**
